import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { fetchShelves, fetchBorrowers, fetchTransactions, fetchAdmins, fetchUsers, fetchApprovals, isSupabaseConfigured, supabase } from './lib/supabase'

const nav = ['Dashboard','Inventory','Shelves','Borrowers','Transactions','Inventory Checks','Reports']
const admin = ['Users','Admin Approvals','Permissions','Activity Logs','Settings']
const Badge = ({children,tone=''}) => <span className={'badge '+tone}>{children}</span>

export default function App() {
  const [page,setPage] = useState('Dashboard')
  const [mobile,setMobile] = useState(false)
  const [query,setQuery] = useState('')
  const [dbShelves,setDbShelves] = useState([])
  const [loading,setLoading] = useState(true)
  const [error,setError] = useState('')
  useEffect(() => { fetchShelves().then(({data,error}) => { if(error) setError(error.message); else setDbShelves(data || []); setLoading(false) }) }, [])
  const shelves = useMemo(() => dbShelves.filter(s => (s.code+' '+s.name+' '+s.item_type).toLowerCase().includes(query.toLowerCase())), [dbShelves,query])
  const units = dbShelves.flatMap(s => s.inventory_units || [])
  const count = status => units.filter(u => u.status === status).length
  const go = name => { setPage(name); setMobile(false) }
  return <div className="app">
    <aside className={mobile ? 'side open' : 'side'}><div className="brand"><b>⌁</b><span><strong>Stockly</strong><small>Inventory system</small></span></div><div className="workspace">● Science Laboratory　⌄</div><label>MAIN MENU</label><nav>{nav.map((n,i)=><button className={page===n?'active':''} onClick={()=>go(n)} key={n}>{['⌂','▤','▥','♙','↔','✓','▥'][i]} {n}</button>)}</nav><label>ADMINISTRATION</label><nav>{admin.map(n=><button className={page===n?'active':''} onClick={()=>go(n)} key={n}>⚙ {n}</button>)}</nav></aside>
    <main><header><button className="mobile" onClick={()=>setMobile(!mobile)}>☰</button><div><label>SUPABASE DATABASE</label><h1>{page}</h1><p>{isSupabaseConfigured?'Live data connection':'Environment variables are missing'}</p></div><div className="head"><span>{isSupabaseConfigured?'Connected':'Not connected'}</span><button className="logout" onClick={()=>supabase?.auth.signOut()}>Log out</button></div></header>
    {error && <div className="connection-error"><b>Database connection error:</b> {error}</div>}
    {page==='Dashboard' && <section className="stats">{[['Total units',units.length,'From Supabase','▤'],['Available',count('available'),'Live inventory count','✓'],['Borrowed',count('borrowed'),'Live inventory count','↗'],['Needs attention',units.filter(u=>u.status==='under_maintenance'||u.condition==='damaged').length,'Damaged or maintenance','!']].map((x,i)=><div className="stat" key={x[0]}><i className={'c'+i}>{x[3]}</i><small>{x[0]}</small><strong>{loading?'…':x[1]}</strong><em>{x[2]}</em></div>)}</section>}
    {(page==='Dashboard'||page==='Shelves'||page==='Inventory') && <section className="card page"><div className="cardhead"><div><h2>{page==='Dashboard'?'Shelves from Supabase':page}</h2><p>{loading?'Loading database records…':shelves.length+' shelf records loaded from Supabase'}</p></div><Badge tone={error?'bad':''}>{loading?'Loading':error?'Error':'Connected'}</Badge></div>{page!=='Dashboard'&&<div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search shelves..."/></div>}{!loading&&!error&&!shelves.length&&<div className="empty">No shelves found. Run seed.sql in Supabase, then refresh.</div>}<div className="shelves">{shelves.map(s=><article className="shelf" key={s.id}><div><i>▥</i><Badge>{(s.inventory_units||[]).filter(u=>u.status==='available').length} available</Badge></div><h2>{s.name}</h2><p>{s.code} · {s.item_type}</p><hr/><small><b>{(s.inventory_units||[]).length}</b> total units <span>{(s.inventory_units||[]).filter(u=>u.status==='borrowed').length} borrowed</span></small></article>)}</div></section>}
    {page!=='Dashboard'&&page!=='Shelves'&&page!=='Inventory'&&<DatabaseTable page={page}/>} 
    </main></div>
}

function DatabaseTable({ page }) {
  const [rows, setRows] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [roleFilter, setRoleFilter] = useState('All')
  useEffect(() => { const load = page === 'Borrowers' ? fetchBorrowers() : page === 'Transactions' ? fetchTransactions() : page === 'Users' ? fetchUsers() : page === 'Admin Approvals' ? fetchApprovals() : Promise.resolve({ data: [] }); load.then(({ data, error }) => { if (error) setError(error.message); else setRows(data || []); setLoading(false) }) }, [page])
  const isBorrowers = page === 'Borrowers', isAdmins = page === 'Admins', isUsers = page === 'Users', isApprovals = page === 'Admin Approvals'
  const visibleUsers = rows.filter(r => roleFilter === 'All' || r.role === roleFilter)
  async function changeRole(user, role) { const from = user.role === 'Admin' ? 'admin_accounts' : 'operator_accounts', to = role === 'Admin' ? 'admin_accounts' : 'operator_accounts'; if (from !== to) { await supabase.from(from).delete().eq('id', user.id); await supabase.from(to).insert({ full_name: user.full_name, email: user.email, status: user.status }) } setRows(rows.map(r => r.id === user.id ? { ...r, role } : r)) }
  if (isUsers) return <section className="card page"><div className="cardhead"><div><h2>Users</h2><p>Manage Admin and Operator accounts</p></div><Badge>{visibleUsers.length} users</Badge></div><div className="toolbar"><div className="search"><input placeholder="Search users..." onChange={e => setRows(rows.filter(r => r.full_name.toLowerCase().includes(e.target.value.toLowerCase()) || r.email.toLowerCase().includes(e.target.value.toLowerCase())))} /></div><select value={roleFilter} onChange={e => setRoleFilter(e.target.value)}><option>All</option><option>Admin</option><option>Operator</option></select></div><table><thead><tr><th>NAME</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>CHANGE ROLE</th></tr></thead><tbody>{visibleUsers.map(r => <tr key={r.id}><td><b>{r.full_name}</b></td><td>{r.email}</td><td><Badge>{r.role}</Badge></td><td>{r.status}</td><td><select value={r.role} onChange={e => changeRole(r,e.target.value)}><option>Admin</option><option>Operator</option></select></td></tr>)}</tbody></table></section>
  async function approve(row, requestedRole) { const table = requestedRole === 'Admin' ? 'admin_accounts' : 'operator_accounts'; const payload = { full_name: row.full_name, email: row.email, status: 'active' }; const added = await supabase.from(table).insert(payload); if (added.error) { setError(added.error.message); return } const changed = await supabase.from('account_approvals').update({ status: 'approved', reviewed_by: 'Current Admin', reviewed_at: new Date().toISOString() }).eq('id', row.id); if (changed.error) setError(changed.error.message); else setRows(rows.filter(item => item.id !== row.id)) }
  if (isApprovals) return <section className="card page"><div className="cardhead"><div><h2>Admin Approvals</h2><p>Choose a role before approving each account</p></div><Badge>{rows.length} requests</Badge></div>{error&&<div className="connection-error">{error}</div>}<table><thead><tr><th>NAME</th><th>EMAIL</th><th>ASSIGN ROLE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.full_name}</b></td><td>{r.email}</td><td>{r.status==='pending'?<select value={r.requested_role} onChange={e=>setRows(rows.map(x=>x.id===r.id?{...x,requested_role:e.target.value}:x))}><option>Admin</option><option>Operator</option></select>:r.requested_role}</td><td><Badge tone={r.status==='pending'?'':'neutral'}>{r.status}</Badge></td><td>{r.status==='pending'&&<button className="primary" onClick={()=>approve(r,r.requested_role)}>Approve</button>}</td></tr>)}</tbody></table></section>
  return <section className="card page"><div className="cardhead"><div><h2>{page}</h2><p>Live records loaded from Supabase</p></div><Badge tone={error ? 'bad' : ''}>{loading ? 'Loading' : error ? 'Error' : rows.length + ' records'}</Badge></div>{error && <div className="connection-error">{error}</div>}{!loading && !error && rows.length === 0 && <div className="empty">No records found in the {page.toLowerCase()} table.</div>}{rows.length > 0 && <table><thead><tr>{(isBorrowers ? ['Name','Student / Employee ID','Created'] : isAdmins ? ['Full name','Email','Status','Created'] : ['Reference','Borrower','Item','Borrowed','Expected return','Returned']).map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r => isBorrowers ? <tr key={r.id}><td><b>{r.name}</b></td><td>{r.identity_number}</td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr> : isAdmins ? <tr key={r.id}><td><b>{r.full_name}</b></td><td>{r.email}</td><td><Badge tone={r.status === 'disabled' ? 'bad' : ''}>{r.status}</Badge></td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr> : <tr key={r.id}><td><b>{r.reference}</b></td><td>{r.borrowers?.name || '—'}</td><td>{r.inventory_units?.shelves?.code || '—'} #{String(r.inventory_units?.unit_number || '').padStart(3,'0')}</td><td>{new Date(r.borrowed_at).toLocaleDateString()}</td><td>{r.expected_return_at}</td><td><Badge tone={r.returned_at ? 'neutral' : ''}>{r.returned_at ? 'Returned' : 'Borrowed'}</Badge></td></tr>)}</tbody></table>}</section>
}
