import { useEffect, useState } from 'react'
import App from './App'
import { supabase } from './lib/supabase'

export default function AuthGate() {
  const [session, setSession] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  const [registering, setRegistering] = useState(false), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [fullName, setFullName] = useState('')
  useEffect(() => { if (!supabase) { setError('Supabase is not configured'); setLoading(false); return }; supabase.auth.getSession().then(({ data }) => data.session ? check(data.session) : setLoading(false)); const { data: listener } = supabase.auth.onAuthStateChange((_event, s) => s ? check(s) : setSession(null)); return () => listener.subscription.unsubscribe() }, [])
  async function check(s) { const { data, error: queryError } = await supabase.from('user_accounts').select('role,status').eq('email', s.user.email).maybeSingle(); if (queryError) setError(queryError.message); else if (data?.status === 'active') setSession(s); else { await supabase.auth.signOut(); setError('Your account is pending approval or disabled.') }; setLoading(false) }
  async function login(e) { e.preventDefault(); setError(''); setLoading(true); const { data, error: loginError } = await supabase.auth.signInWithPassword({ email, password }); if (loginError) { setError(loginError.message); setLoading(false) } else check(data.session) }
  async function register(e) { e.preventDefault(); setError(''); setLoading(true); const { data, error: signupError } = await supabase.auth.signUp({ email, password }); if (signupError) { setError(signupError.message); setLoading(false); return }; const { error: approvalError } = await supabase.from('account_approvals').insert({ full_name: fullName, email, assigned_role: 'Operator', status: 'pending' }); if (approvalError) { setError(approvalError.message); setLoading(false); return }; if (data.session) await supabase.auth.signOut(); setRegistering(false); setLoading(false); setError('Account created. An administrator must approve it before you can sign in.'); setPassword('') }
  if (loading) return <div className="login-screen"><div className="login-card">Connecting securely…</div></div>
  if (session) return <App />
  return <div className="login-screen"><form className="login-card" onSubmit={registering ? register : login}><div className="login-logo">⌁</div><p className="eyebrow">INVENTORY SYSTEM</p><h2>{registering ? 'Create an account' : 'Welcome back'}</h2><p>{registering ? 'Request access to continue.' : 'Sign in to continue.'}</p>{error && <div className="login-error">{error}</div>}{registering && <label>Full name<input value={fullName} onChange={e => setFullName(e.target.value)} required /></label>}<label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} minLength="6" required /></label><button className="primary login-button">{registering ? 'Request operator access' : 'Sign in to Stockly'}</button><button type="button" className="auth-switch" onClick={() => { setRegistering(!registering); setError('') }}>{registering ? 'Back to sign in' : 'Create an account'}</button></form></div>
}
